/* =======  SCRIPTS DE EXCLUSÃO  ======= */

-- EXCLUI TABELA USUARIO
DROP TABLE usuario CASCADE CONSTRAINTS;

-- EXCLUI TABELA ENDERECO
DROP TABLE endereco CASCADE CONSTRAINTS;

-- EXCLUI TABELA BANCO
DROP TABLE banco CASCADE CONSTRAINTS;

-- EXCLUI TABELA CARTAO
DROP TABLE cartao CASCADE CONSTRAINTS;

-- EXCLUI TABELA VEICULO
DROP TABLE veiculo CASCADE CONSTRAINTS;

-- EXCLUI TABELA ANUNCIO
DROP TABLE anuncio CASCADE CONSTRAINTS;

-- EXCLUI TABELA AGENDAMENTO
DROP TABLE agendamento CASCADE CONSTRAINTS;

-- EXCLUI TABELA REGISTRO
DROP TABLE registro CASCADE CONSTRAINTS;

-- EXCLUI USUARIO SEQUENCE
DROP SEQUENCE usuario_seq;

-- EXCLUI ENDERECO SEQUENCE
DROP SEQUENCE endereco_seq;

-- EXCLUI BANCO SEQUENCE
DROP SEQUENCE banco_seq;

-- EXCLUI CARTAO SEQUENCE
DROP SEQUENCE cartao_seq;

-- EXCLUI VEICULO SEQUENCE
DROP SEQUENCE veiculo_seq;

-- EXCLUI ANUNCIO SEQUENCE
DROP SEQUENCE anuncio_seq;

-- EXCLUI AGENDAMENTO SEQUENCE
DROP SEQUENCE agendamento_seq;

-- EXCLUI REGISTRO SEQUENCE
DROP SEQUENCE registro_seq;
