/* =======  SCRIPTS DE EXCLUSÃO  ======= */

-- EXCLUI TABELA USUARIO
DROP TABLE usuario CASCADE CONSTRAINTS;

-- EXCLUI TABELA ENDERECO
DROP TABLE endereco CASCADE CONSTRAINTS;

-- EXCLUI TABELA BANCO
DROP TABLE banco CASCADE CONSTRAINTS;

-- EXCLUI TABELA CARTAO
DROP TABLE cartao CASCADE CONSTRAINTS;

-- EXCLUI TABELA VEICULO
DROP TABLE veiculo CASCADE CONSTRAINTS;

-- EXCLUI TABELA ANUNCIO
DROP TABLE anuncio CASCADE CONSTRAINTS;

-- EXCLUI TABELA SERVICO
DROP TABLE servico CASCADE CONSTRAINTS;

-- EXCLUI USUARIO SEQUENCE
DROP SEQUENCE usuario_seq;

-- EXCLUI USUARIO SEQUENCE
DROP SEQUENCE endereco_seq;

-- EXCLUI USUARIO SEQUENCE
DROP SEQUENCE banco_seq;

-- EXCLUI USUARIO SEQUENCE
DROP SEQUENCE cartao_seq;

-- EXCLUI USUARIO SEQUENCE
DROP SEQUENCE veiculo_seq;

-- EXCLUI USUARIO SEQUENCE
DROP SEQUENCE anuncio_seq;

-- EXCLUI USUARIO SEQUENCE
DROP SEQUENCE servico_seq;
