/* =======  SCRIPTS DE EXCLUSÃO  ======= */

-- TODO DROP SEQUENCES

-- EXCLUI TABELA USUARIO
DROP TABLE usuario CASCADE CONSTRAINTS;

-- EXCLUI TABELA ENDERECO
DROP TABLE endereco CASCADE CONSTRAINTS;

-- EXCLUI TABELA BANCO
DROP TABLE banco CASCADE CONSTRAINTS;

-- EXCLUI TABELA CARTAO
DROP TABLE cartao CASCADE CONSTRAINTS;

-- EXCLUI TABELA VEICULO
DROP TABLE veiculo CASCADE CONSTRAINTS;

-- EXCLUI TABELA ANUNCIO
DROP TABLE anuncio CASCADE CONSTRAINTS;

-- EXCLUI TABELA SERVICO
DROP TABLE servico CASCADE CONSTRAINTS;

