package br.com.gopark.enums;

public enum Marca {

    CHEVROLET, VOLKSWAGEN, FIAT, HYUNDAI, NISSAN, RENAULT, FORD, TOYOTA, JEEP, HONDA, CITROEN,
    MITSUBISHI, PEUGEOT, CHERY, BMW, MERCEDES, KIA, AUDI, VOLVO, LANDROVER, AIMA, AVELLOZ, BRAVAX,
    BRP, BULL, DAFRA, DAYANG, DUCATI, HAOJUE, HARLEYDAVIDSON, HUSQVARNA, INDIAN, IROS, JONNY, KASINSKI, KAWASAKI,
    KTM, KYMCO, MOTOCAR, MVAGUSTA, PIAGGIO, ROYALENFIELD, SHINERAY, SUZUKI, SWM, TRAXX, TRIUMPH, VESPA, WUYANG, YAMAHA

}
